# Generated by Django 3.2.6 on 2021-08-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210824_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortestingonly',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
