# Generated by Django 3.2.6 on 2021-08-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_physicalstocktable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalstocktable',
            old_name='quantity_in_store',
            new_name='quantity',
        ),
    ]
