# Generated by Django 3.2.6 on 2021-08-24 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_auto_20210824_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer1',
            new_name='Customer',
        ),
    ]
