# Generated by Django 3.2.6 on 2021-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_receive_quantity_physicalstocktable_received_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalstocktable',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstocktable',
            name='part_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='physicalstocktable',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='physicalstocktable',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
