# Generated by Django 3.2.6 on 2021-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210825_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalstocktable',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalstocktable',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
