# Generated by Django 3.2.6 on 2021-08-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210825_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalstocktable',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
