# Generated by Django 3.2.6 on 2021-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210825_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalstocktable',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='physicalstocktable',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='physicalstocktable',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='physicalstocktable',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='physicalstocktable',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='physicalstocktable',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
