# Generated by Django 3.2.6 on 2021-08-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210827_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalstocktable',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
