# Generated by Django 3.2.6 on 2021-09-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_jshtmltest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jshtmltest',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jshtmltest',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
