# Generated by Django 3.2.6 on 2021-09-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_auto_20210904_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodeltest',
            name='subject',
        ),
    ]
