# Generated by Django 3.2.6 on 2021-09-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_remove_formmodeltest_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formmodeltest',
        ),
    ]
