# Generated by Django 3.2.6 on 2021-09-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20210904_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest_0',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest_2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
