# Generated by Django 3.2.6 on 2021-09-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_auto_20210904_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ModelAndFormTogether',
        ),
        migrations.DeleteModel(
            name='ProfileInterest',
        ),
    ]
