# Generated by Django 3.2.6 on 2021-09-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20210904_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profileuyougsd',
        ),
    ]
