# Generated by Django 3.2.6 on 2021-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_delete_profileuyougsd'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedPhysicalStockTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issued_to', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
