# Generated by Django 3.2.6 on 2021-09-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_issuedphysicalstocktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedphysicalstocktable',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
