# Generated by Django 3.2.6 on 2021-09-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_issuedphysicalstocktable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedphysicalstocktable',
            name='received_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
