# Generated by Django 3.2.6 on 2021-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_issuedphysicalstocktable_received_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=220)),
                ('lname', models.CharField(max_length=220)),
            ],
        ),
    ]
