# Generated by Django 3.2.6 on 2021-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_namestable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormThreeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dynamicformthreetable',
            },
        ),
    ]
