# Generated by Django 3.2.6 on 2021-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_quotationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtable',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
