# Generated by Django 3.2.6 on 2021-09-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_alter_sellingpricecalcmodel_markup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpricecalcmodel',
            name='markup',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
