# Generated by Django 3.2.6 on 2021-09-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_sellingpricecalcmodel_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForTestingOnly',
        ),
    ]
