# Generated by Django 3.2.6 on 2021-09-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_delete_fortestingonly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationtable',
            name='customer',
        ),
        migrations.AddField(
            model_name='quotationtable',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationtable',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
