# Generated by Django 3.2.6 on 2021-10-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20211006_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
