# Generated by Django 3.2.6 on 2021-10-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passengersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengersmodel',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='flights.FlightModel'),
        ),
    ]
