# Generated by Django 3.2.6 on 2021-09-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('invoiceDueDate', models.DateField(blank=True, null=True)),
                ('paymentTerms', models.CharField(choices=[('15 days', '15 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='15 days', max_length=100)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Current', 'Current'), ('Overdue', 'Overdue')], default='Current', max_length=100)),
                ('comments', models.CharField(blank=True, default='invoice', max_length=250, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('dateCreated', models.DateTimeField(blank=True, null=True)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.clientsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unitPrice', models.FloatField(blank=True, null=True)),
                ('totalAmount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('$', 'USD'), ('Euro', 'Euro')], default='$', max_length=100)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('dateCreated', models.DateTimeField(blank=True, null=True)),
                ('lastUpdated', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoicesmodel')),
            ],
        ),
    ]
