# Generated by Django 3.2.6 on 2021-09-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoicesmodel_productsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesmodel',
            name='paymentTerms',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Deposit', 'Deposit'), ('15 days', '15 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='15 days', max_length=100),
        ),
    ]
